 [general]
 live_config_reload = true
 working_directory = "None"
#
# # Themes --
# import = [ 
#   "~/.config/alacritty/nordic.toml",
#   "~/.config/alacritty/keybinds.toml"
# ]
#
 [window]

 startup_mode = "Maximized"
 decorations = "None"
# blur = true
# opacity = 0.9
# padding.x = 10
# padding.y = 10

# [window.dimensions]
# columns = 160
# lines = 80
#
 [cursor.style]
 shape= "Beam"
 blinking = "Never"

 [colors]
 transparent_background_colors = true
 draw_bold_text_with_bright_colors = true

 [env]
 TERM = "xterm-256color"

 [font]
 glyph_offset = { x = 1, y = 0 }
 normal.family = "JetBrainsMonoNL Nerd Font"
 normal.style = "Regular"
 size = 15.0

 [font.bold]
 family ="JetBrainsMonoNL Nerd Font" 
 style = "Bold"

 [font.italic]
 family ="JetBrainsMonoNL Nerd Font" 
 style = "Italic"
